[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true

[profile.0_6_12]
# Separate profile for Solidity 0.6.12 with different source and library paths
src = 'src_rootsock'
out = 'out'
libs = ['lib/rif-relay-contracts', 'lib']
solc_version = '0.6.12'

[rpc_endpoints]
rootstock = "${ROOTSTOCK_RPC_URL}"
fhenix = "${FHENIX_RPC_URL}"

[etherscan]
rootstock = { key = "${ROOTSTOCK_ETHERSCAN_API_KEY}", url = "https://rpc.testnet.rootstock.io/dpX0WV1RJzbWdMUpybG44cYyeDwVXW-T" }
fhenix = { key = "${FHENIX_ETHERSCAN_API_KEY}", url = "https://api.fhenix.explorer.io/api" }

[doc]
title = 'RuneTrust Contracts'
