[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
rootstock = "${ROOTSTOCK_RPC_URL}"
fhenix = "${FHENIX_RPC_URL}"

[etherscan]
rootstock = { key = "${ROOTSTOCK_ETHERSCAN_API_KEY}", url = "https://rpc.testnet.rootstock.io/dpX0WV1RJzbWdMUpybG44cYyeDwVXW-T" }
fhenix = { key = "${FHENIX_ETHERSCAN_API_KEY}", url = "https://api.fhenix.explorer.io/api" }

[doc]
title = 'RuneTrust Contracts'
